package nju.software.xfgl.model;

// Generated 2014-7-21 0:36:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DsrGr generated by hbm2java
 */
public class DsrGr implements java.io.Serializable 
{
	private static final long serialVersionUID = 1L;
	
	private Integer ajxh;
	
	private Integer dsrbh;
	
	private String xm;
	private String xb;
	private Date csnyr;
	private String mz;
	private String jg;
	private String zy;
	private String zw;
	private String whcd;
	private String gzdw;
	private String zzmm;
	private String jb;
	private String sf;
	private String hyqk;
	private String jtqk;
	private String jkqk;
	private String ssgj;
	private String sfzhm;
	private String yb;
	private String dh;
	private String dz;
	private String qrjg;
	private String qrgc;
	private String zzd;
	private String zwzy;
	private String zjlbF;
	private String zjlb;
	private String zjlbB;
	private String zjlbC;
	private String zjlbE;
	private int symbol;

	public DsrGr() {
	}

	public DsrGr(Integer ajxh, Integer dsrbh, int symbol) {
		this.ajxh = ajxh;
		this.dsrbh = dsrbh;
		this.symbol = symbol;
	}

	public DsrGr(Integer ajxh, Integer dsrbh, String xm, String xb, Date csnyr, String mz,
			String jg, String zy, String zw, String whcd, String gzdw,
			String zzmm, String jb, String sf, String hyqk, String jtqk,
			String jkqk, String ssgj, String sfzhm, String yb, String dh,
			String dz, String qrjg, String qrgc, String zzd, String zwzy,
			String zjlbF, String zjlb, String zjlbB, String zjlbC,
			String zjlbE, int symbol) {
		this.ajxh = ajxh;
		this.dsrbh = dsrbh;
		this.xm = xm;
		this.xb = xb;
		this.csnyr = csnyr;
		this.mz = mz;
		this.jg = jg;
		this.zy = zy;
		this.zw = zw;
		this.whcd = whcd;
		this.gzdw = gzdw;
		this.zzmm = zzmm;
		this.jb = jb;
		this.sf = sf;
		this.hyqk = hyqk;
		this.jtqk = jtqk;
		this.jkqk = jkqk;
		this.ssgj = ssgj;
		this.sfzhm = sfzhm;
		this.yb = yb;
		this.dh = dh;
		this.dz = dz;
		this.qrjg = qrjg;
		this.qrgc = qrgc;
		this.zzd = zzd;
		this.zwzy = zwzy;
		this.zjlbF = zjlbF;
		this.zjlb = zjlb;
		this.zjlbB = zjlbB;
		this.zjlbC = zjlbC;
		this.zjlbE = zjlbE;
		this.symbol = symbol;
	}


	public Integer getAjxh() {
		return ajxh;
	}

	public void setAjxh(Integer ajxh) {
		this.ajxh = ajxh;
	}

	public Integer getDsrbh() {
		return dsrbh;
	}

	public void setDsrbh(Integer dsrbh) {
		this.dsrbh = dsrbh;
	}

	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	public String getXb() {
		return this.xb;
	}

	public void setXb(String xb) {
		this.xb = xb;
	}

	public Date getCsnyr() {
		return this.csnyr;
	}

	public void setCsnyr(Date csnyr) {
		this.csnyr = csnyr;
	}

	public String getMz() {
		return this.mz;
	}

	public void setMz(String mz) {
		this.mz = mz;
	}

	public String getJg() {
		return this.jg;
	}

	public void setJg(String jg) {
		this.jg = jg;
	}

	public String getZy() {
		return this.zy;
	}

	public void setZy(String zy) {
		this.zy = zy;
	}

	public String getZw() {
		return this.zw;
	}

	public void setZw(String zw) {
		this.zw = zw;
	}

	public String getWhcd() {
		return this.whcd;
	}

	public void setWhcd(String whcd) {
		this.whcd = whcd;
	}

	public String getGzdw() {
		return this.gzdw;
	}

	public void setGzdw(String gzdw) {
		this.gzdw = gzdw;
	}

	public String getZzmm() {
		return this.zzmm;
	}

	public void setZzmm(String zzmm) {
		this.zzmm = zzmm;
	}

	public String getJb() {
		return this.jb;
	}

	public void setJb(String jb) {
		this.jb = jb;
	}

	public String getSf() {
		return this.sf;
	}

	public void setSf(String sf) {
		this.sf = sf;
	}

	public String getHyqk() {
		return this.hyqk;
	}

	public void setHyqk(String hyqk) {
		this.hyqk = hyqk;
	}

	public String getJtqk() {
		return this.jtqk;
	}

	public void setJtqk(String jtqk) {
		this.jtqk = jtqk;
	}

	public String getJkqk() {
		return this.jkqk;
	}

	public void setJkqk(String jkqk) {
		this.jkqk = jkqk;
	}

	public String getSsgj() {
		return this.ssgj;
	}

	public void setSsgj(String ssgj) {
		this.ssgj = ssgj;
	}

	public String getSfzhm() {
		return this.sfzhm;
	}

	public void setSfzhm(String sfzhm) {
		this.sfzhm = sfzhm;
	}

	public String getYb() {
		return this.yb;
	}

	public void setYb(String yb) {
		this.yb = yb;
	}

	public String getDh() {
		return this.dh;
	}

	public void setDh(String dh) {
		this.dh = dh;
	}

	public String getDz() {
		return this.dz;
	}

	public void setDz(String dz) {
		this.dz = dz;
	}

	public String getQrjg() {
		return this.qrjg;
	}

	public void setQrjg(String qrjg) {
		this.qrjg = qrjg;
	}

	public String getQrgc() {
		return this.qrgc;
	}

	public void setQrgc(String qrgc) {
		this.qrgc = qrgc;
	}

	public String getZzd() {
		return this.zzd;
	}

	public void setZzd(String zzd) {
		this.zzd = zzd;
	}

	public String getZwzy() {
		return this.zwzy;
	}

	public void setZwzy(String zwzy) {
		this.zwzy = zwzy;
	}

	public String getZjlbF() {
		return this.zjlbF;
	}

	public void setZjlbF(String zjlbF) {
		this.zjlbF = zjlbF;
	}

	public String getZjlb() {
		return this.zjlb;
	}

	public void setZjlb(String zjlb) {
		this.zjlb = zjlb;
	}

	public String getZjlbB() {
		return this.zjlbB;
	}

	public void setZjlbB(String zjlbB) {
		this.zjlbB = zjlbB;
	}

	public String getZjlbC() {
		return this.zjlbC;
	}

	public void setZjlbC(String zjlbC) {
		this.zjlbC = zjlbC;
	}

	public String getZjlbE() {
		return this.zjlbE;
	}

	public void setZjlbE(String zjlbE) {
		this.zjlbE = zjlbE;
	}

	public int getSymbol() {
		return this.symbol;
	}

	public void setSymbol(int symbol) {
		this.symbol = symbol;
	}

}
