package nju.software.xfgl.model;

// Generated 2014-7-21 0:36:58 by Hibernate Tools 3.4.0.CR1

/**
 * DsrXpJg generated by hbm2java
 */
public class DsrXpJg implements java.io.Serializable 
{
	private static final long serialVersionUID = 1L;

	private Integer ajxh;
	
	private Integer dsrbh;
	
	private String jgmc;
	private String xzjgxz;
	private String sffy;
	private String sfpc;
	private String dh;
	private String dz;
	private String yb;
	private String fddbrxm;
	private String djzlb;
	private String djzh;
	private String djzlbA;
	private String djzhA;
	private String djzlbB;
	private String djzhB;
	private String djzlbC;
	private String djzhC;
	private String djzlbE;
	private String djzhE;
	private int symbol;

	public DsrXpJg() {
	}

	public DsrXpJg(Integer ajxh, Integer dsrbh, int symbol) {
		this.ajxh = ajxh;
		this.dsrbh = dsrbh;
		this.symbol = symbol;
	}

	public DsrXpJg(Integer ajxh, Integer dsrbh, String jgmc, String xzjgxz, String sffy,
			String sfpc, String dh, String dz, String yb, String fddbrxm,
			String djzlb, String djzh, String djzlbA, String djzhA,
			String djzlbB, String djzhB, String djzlbC, String djzhC,
			String djzlbE, String djzhE, int symbol) {
		this.ajxh = ajxh;
		this.dsrbh = dsrbh;
		this.jgmc = jgmc;
		this.xzjgxz = xzjgxz;
		this.sffy = sffy;
		this.sfpc = sfpc;
		this.dh = dh;
		this.dz = dz;
		this.yb = yb;
		this.fddbrxm = fddbrxm;
		this.djzlb = djzlb;
		this.djzh = djzh;
		this.djzlbA = djzlbA;
		this.djzhA = djzhA;
		this.djzlbB = djzlbB;
		this.djzhB = djzhB;
		this.djzlbC = djzlbC;
		this.djzhC = djzhC;
		this.djzlbE = djzlbE;
		this.djzhE = djzhE;
		this.symbol = symbol;
	}

	public Integer getAjxh() {
		return ajxh;
	}

	public void setAjxh(Integer ajxh) {
		this.ajxh = ajxh;
	}

	public Integer getDsrbh() {
		return dsrbh;
	}

	public void setDsrbh(Integer dsrbh) {
		this.dsrbh = dsrbh;
	}

	public String getJgmc() {
		return this.jgmc;
	}

	public void setJgmc(String jgmc) {
		this.jgmc = jgmc;
	}

	public String getXzjgxz() {
		return this.xzjgxz;
	}

	public void setXzjgxz(String xzjgxz) {
		this.xzjgxz = xzjgxz;
	}

	public String getSffy() {
		return this.sffy;
	}

	public void setSffy(String sffy) {
		this.sffy = sffy;
	}

	public String getSfpc() {
		return this.sfpc;
	}

	public void setSfpc(String sfpc) {
		this.sfpc = sfpc;
	}

	public String getDh() {
		return this.dh;
	}

	public void setDh(String dh) {
		this.dh = dh;
	}

	public String getDz() {
		return this.dz;
	}

	public void setDz(String dz) {
		this.dz = dz;
	}

	public String getYb() {
		return this.yb;
	}

	public void setYb(String yb) {
		this.yb = yb;
	}

	public String getFddbrxm() {
		return this.fddbrxm;
	}

	public void setFddbrxm(String fddbrxm) {
		this.fddbrxm = fddbrxm;
	}

	public String getDjzlb() {
		return this.djzlb;
	}

	public void setDjzlb(String djzlb) {
		this.djzlb = djzlb;
	}

	public String getDjzh() {
		return this.djzh;
	}

	public void setDjzh(String djzh) {
		this.djzh = djzh;
	}

	public String getDjzlbA() {
		return this.djzlbA;
	}

	public void setDjzlbA(String djzlbA) {
		this.djzlbA = djzlbA;
	}

	public String getDjzhA() {
		return this.djzhA;
	}

	public void setDjzhA(String djzhA) {
		this.djzhA = djzhA;
	}

	public String getDjzlbB() {
		return this.djzlbB;
	}

	public void setDjzlbB(String djzlbB) {
		this.djzlbB = djzlbB;
	}

	public String getDjzhB() {
		return this.djzhB;
	}

	public void setDjzhB(String djzhB) {
		this.djzhB = djzhB;
	}

	public String getDjzlbC() {
		return this.djzlbC;
	}

	public void setDjzlbC(String djzlbC) {
		this.djzlbC = djzlbC;
	}

	public String getDjzhC() {
		return this.djzhC;
	}

	public void setDjzhC(String djzhC) {
		this.djzhC = djzhC;
	}

	public String getDjzlbE() {
		return this.djzlbE;
	}

	public void setDjzlbE(String djzlbE) {
		this.djzlbE = djzlbE;
	}

	public String getDjzhE() {
		return this.djzhE;
	}

	public void setDjzhE(String djzhE) {
		this.djzhE = djzhE;
	}

	public int getSymbol() {
		return this.symbol;
	}

	public void setSymbol(int symbol) {
		this.symbol = symbol;
	}

}
