package nju.software.xfgl.model;

// Generated 2014-7-21 0:36:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LaLasq generated by hbm2java
 */
public class LaLasq implements java.io.Serializable 
{
	private static final long serialVersionUID = 1L;
	
	private int lasqbh;
	private String zrrbh;
	private String frbh;
	private String xzjgbh;
	private Date lasqrq;
	private String cl;
	private String aqsm;
	private String cxbh;
	private String lacxmm;
	private String dzyj;
	private String lxdh;
	private int symbol;

	public LaLasq() {
	}

	public LaLasq(int lasqbh, String aqsm, String cxbh, String lacxmm,
			int symbol) {
		this.lasqbh = lasqbh;
		this.aqsm = aqsm;
		this.cxbh = cxbh;
		this.lacxmm = lacxmm;
		this.symbol = symbol;
	}

	public LaLasq(int lasqbh, String zrrbh, String frbh, String xzjgbh,
			Date lasqrq, String cl, String aqsm, String cxbh, String lacxmm,
			String dzyj, String lxdh, int symbol) {
		this.lasqbh = lasqbh;
		this.zrrbh = zrrbh;
		this.frbh = frbh;
		this.xzjgbh = xzjgbh;
		this.lasqrq = lasqrq;
		this.cl = cl;
		this.aqsm = aqsm;
		this.cxbh = cxbh;
		this.lacxmm = lacxmm;
		this.dzyj = dzyj;
		this.lxdh = lxdh;
		this.symbol = symbol;
	}

	public int getLasqbh() {
		return this.lasqbh;
	}

	public void setLasqbh(int lasqbh) {
		this.lasqbh = lasqbh;
	}

	public String getZrrbh() {
		return this.zrrbh;
	}

	public void setZrrbh(String zrrbh) {
		this.zrrbh = zrrbh;
	}

	public String getFrbh() {
		return this.frbh;
	}

	public void setFrbh(String frbh) {
		this.frbh = frbh;
	}

	public String getXzjgbh() {
		return this.xzjgbh;
	}

	public void setXzjgbh(String xzjgbh) {
		this.xzjgbh = xzjgbh;
	}

	public Date getLasqrq() {
		return this.lasqrq;
	}

	public void setLasqrq(Date lasqrq) {
		this.lasqrq = lasqrq;
	}

	public String getCl() {
		return this.cl;
	}

	public void setCl(String cl) {
		this.cl = cl;
	}

	public String getAqsm() {
		return this.aqsm;
	}

	public void setAqsm(String aqsm) {
		this.aqsm = aqsm;
	}

	public String getCxbh() {
		return this.cxbh;
	}

	public void setCxbh(String cxbh) {
		this.cxbh = cxbh;
	}

	public String getLacxmm() {
		return this.lacxmm;
	}

	public void setLacxmm(String lacxmm) {
		this.lacxmm = lacxmm;
	}

	public String getDzyj() {
		return this.dzyj;
	}

	public void setDzyj(String dzyj) {
		this.dzyj = dzyj;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public int getSymbol() {
		return this.symbol;
	}

	public void setSymbol(int symbol) {
		this.symbol = symbol;
	}

}
