package nju.software.xfgl.model;

// Generated 2014-7-21 0:36:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * XfglLfdj generated by hbm2java
 */
public class XfglLfdj implements java.io.Serializable 
{
	private static final long serialVersionUID = 1L;
	
	private int bh;
	private String djr;
	private Date djrq;
	private String zylfzxm;
	private String sfzhm;
	private String xb;
	private Integer nl;
	private String dh;
	private String zz;
	private String xzz;
	private String gzdw;
	private String dsrxm;
	private String ydsrgx;
	private String lfcxbh;
	private String jgcxmm;
	private String yzbm;
	private String mobilephone;
	private String dzyj;
	private String xfrsf;
	private String fyqk;
	private String qtnr;
	private String attachment;
	private String fkfs;
	private int symbol;

	public XfglLfdj() {
	}

	public XfglLfdj(int bh, String lfcxbh, String jgcxmm, String yzbm,
			String mobilephone, String dzyj, String xfrsf, String fyqk,
			int symbol) {
		this.bh = bh;
		this.lfcxbh = lfcxbh;
		this.jgcxmm = jgcxmm;
		this.yzbm = yzbm;
		this.mobilephone = mobilephone;
		this.dzyj = dzyj;
		this.xfrsf = xfrsf;
		this.fyqk = fyqk;
		this.symbol = symbol;
	}

	public XfglLfdj(int bh, String djr, Date djrq, String zylfzxm,
			String sfzhm, String xb, Integer nl, String dh, String zz,
			String xzz, String gzdw, String dsrxm, String ydsrgx,
			String lfcxbh, String jgcxmm, String yzbm, String mobilephone,
			String dzyj, String xfrsf, String fyqk, String qtnr,
			String attachment, String fkfs, int symbol) {
		this.bh = bh;
		this.djr = djr;
		this.djrq = djrq;
		this.zylfzxm = zylfzxm;
		this.sfzhm = sfzhm;
		this.xb = xb;
		this.nl = nl;
		this.dh = dh;
		this.zz = zz;
		this.xzz = xzz;
		this.gzdw = gzdw;
		this.dsrxm = dsrxm;
		this.ydsrgx = ydsrgx;
		this.lfcxbh = lfcxbh;
		this.jgcxmm = jgcxmm;
		this.yzbm = yzbm;
		this.mobilephone = mobilephone;
		this.dzyj = dzyj;
		this.xfrsf = xfrsf;
		this.fyqk = fyqk;
		this.qtnr = qtnr;
		this.attachment = attachment;
		this.fkfs = fkfs;
		this.symbol = symbol;
	}

	public int getBh() {
		return this.bh;
	}

	public void setBh(int bh) {
		this.bh = bh;
	}

	public String getDjr() {
		return this.djr;
	}

	public void setDjr(String djr) {
		this.djr = djr;
	}

	public Date getDjrq() {
		return this.djrq;
	}

	public void setDjrq(Date djrq) {
		this.djrq = djrq;
	}

	public String getZylfzxm() {
		return this.zylfzxm;
	}

	public void setZylfzxm(String zylfzxm) {
		this.zylfzxm = zylfzxm;
	}

	public String getSfzhm() {
		return this.sfzhm;
	}

	public void setSfzhm(String sfzhm) {
		this.sfzhm = sfzhm;
	}

	public String getXb() {
		return this.xb;
	}

	public void setXb(String xb) {
		this.xb = xb;
	}

	public Integer getNl() {
		return this.nl;
	}

	public void setNl(Integer nl) {
		this.nl = nl;
	}

	public String getDh() {
		return this.dh;
	}

	public void setDh(String dh) {
		this.dh = dh;
	}

	public String getZz() {
		return this.zz;
	}

	public void setZz(String zz) {
		this.zz = zz;
	}

	public String getXzz() {
		return this.xzz;
	}

	public void setXzz(String xzz) {
		this.xzz = xzz;
	}

	public String getGzdw() {
		return this.gzdw;
	}

	public void setGzdw(String gzdw) {
		this.gzdw = gzdw;
	}

	public String getDsrxm() {
		return this.dsrxm;
	}

	public void setDsrxm(String dsrxm) {
		this.dsrxm = dsrxm;
	}

	public String getYdsrgx() {
		return this.ydsrgx;
	}

	public void setYdsrgx(String ydsrgx) {
		this.ydsrgx = ydsrgx;
	}

	public String getLfcxbh() {
		return this.lfcxbh;
	}

	public void setLfcxbh(String lfcxbh) {
		this.lfcxbh = lfcxbh;
	}

	public String getJgcxmm() {
		return this.jgcxmm;
	}

	public void setJgcxmm(String jgcxmm) {
		this.jgcxmm = jgcxmm;
	}

	public String getYzbm() {
		return this.yzbm;
	}

	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}

	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getDzyj() {
		return this.dzyj;
	}

	public void setDzyj(String dzyj) {
		this.dzyj = dzyj;
	}

	public String getXfrsf() {
		return this.xfrsf;
	}

	public void setXfrsf(String xfrsf) {
		this.xfrsf = xfrsf;
	}

	public String getFyqk() {
		return this.fyqk;
	}

	public void setFyqk(String fyqk) {
		this.fyqk = fyqk;
	}

	public String getQtnr() {
		return this.qtnr;
	}

	public void setQtnr(String qtnr) {
		this.qtnr = qtnr;
	}

	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	public String getFkfs() {
		return this.fkfs;
	}

	public void setFkfs(String fkfs) {
		this.fkfs = fkfs;
	}

	public int getSymbol() {
		return this.symbol;
	}

	public void setSymbol(int symbol) {
		this.symbol = symbol;
	}

}
